language: go
go:
- '1.12'
env:
- PATH=/home/travis/gopath/bin:$PATH GO111MODULE=on
script: 
- go test
- go build
before_deploy:
- go get -v github.com/mitchellh/gox
- gox -output build/{{.OS}}_{{.Arch}}/{{.Dir}}
- cd build
- for osarch in * ; do cd $osarch && zip -r ../metrin-$osarch.zip . && cd ../ ; done
- cd ../
deploy:
  provider: releases
  api_key:
    secure: kMPC4tbS94NqFopLvm7GTLT3tOscCSnNwdBicI1kkHcUGavWUSa12IhMiKu1mhizvviQvm7NqcRAdVqTifVXBIxviteGTtbDaaqvRjau4aDnZb8MMGG05Cm8PkGK2I20l/1ArvNAQrWypnp3qfJNxwMP5DnmugzooMjBZN3zhUcu52YuvdCKD8zQEH0EWC/UhluG0kIgRjPun50CUADO+22PTPfjEtoxFmfeZhTx4GUlNniKESIX1L8Eba4nE9uHaivyZR5CewPlJA/SiuTtRFlQZQPD9sSaMq7fc2/zumd1ZReXYPX+b+rNUxeX9OrGmq1Nn+piinVl5zwpzEEpc3SkayDJLyhajGPBwXvola1cA5o6h6SMNddi7HUnFxHliWK0z3pfi51OX9MccL2klHCtHHh7nx7l2trhC9S8KEHhRp2qvCQ19IZ9mYs8IfY6mt7JS2ZsAK/KR8YnJutbGpi1sxtm3DIFtIKrAIZRImh79e3bol7O5Bgn3urLmJaQzm+48WcNuAn8gno1+Ulq1BmxDcA6KgsZr/HJRcSIFxVzsO/YCKIN8uT1LQDzTjGpXoxBTuBU9CRauUXNK+ZwtfIFHK4ZodyvBXX08H9JGal3YCJ1cr4xJNsS1SQjK/8rOjLCA3tDGPGpA5hQHtWnJznnxnp1tS/aRSecWwBbXXk=
  file:
  - build/metrin-darwin_386.zip
  - build/metrin-darwin_amd64.zip
  - build/metrin-freebsd_386.zip
  - build/metrin-freebsd_amd64.zip
  - build/metrin-freebsd_arm.zip
  - build/metrin-linux_386.zip
  - build/metrin-linux_amd64.zip
  - build/metrin-linux_arm.zip
  - build/metrin-netbsd_386.zip
  - build/metrin-netbsd_amd64.zip
  - build/metrin-netbsd_arm.zip
  - build/metrin-openbsd_386.zip
  - build/metrin-openbsd_amd64.zip
  - build/metrin-windows_386.zip
  - build/metrin-windows_amd64.zip
  skip_cleanup: true
  all_branches: true
  on:
    repo: dtakamoto/metrin
    branch: modify-dimensions-value-parse-and-use-cli.v1
    tags: false
